antora:
  extensions:
  - require: '@springio/antora-extensions'
    root_component_name: 'security'
site:
  title: Spring Security
  url: https://docs.spring.io/spring-security/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-security
    branches: [main, '6.{4..5}.x', '{7..99}.*.x']
    tags: ['6.{4..5}.*','{7..99}.*']
    start_path: docs
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-security
    page-related-doc-categories: security
    page-related-doc-projects: framework,graphql
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
  - '@springio/asciidoctor-extensions/javadoc-extension'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.20/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
