antora:
  extensions:
  - ./lib/antora/extensions/inject-collector-config.js
  - '@antora/collector-extension'
  - ./lib/antora/extensions/version-fix.js
  - '@opendevise/antora-release-line-extension'
  - require: '@springio/antora-extensions/tabs-migration-extension'
    # uncomment this option to save the migrated content to the worktree
    #save_result: true
    unwrap_example_block: always
site:
  title: Spring Security
  url: https://docs.spring.io/spring-security/reference
content:
  sources:
  - url: .
    branches: [main, '5.{{6..9},{1..9}+({0..9})}.x', '6.+({0..9}).x']
    worktrees: true # automatically discovers worktrees, if present; otherwise, will use git tree
    tags: ['5.{{6..9},{1..9}+({0..9})}.+({0..9})?(-RC+({0..9}))', '6.+({0..9}).+({0..9})?(-{RC,M}*)']
    start_path: docs
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
urls:
  latest_version_segment: ''
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
