site:
  title: Spring Security
  url: https://docs.spring.io/spring-security/reference/
asciidoc:
  attributes:
    page-pagination: true
content:
  sources:
    - url: https://github.com/spring-io/spring-generated-docs
      branches: [spring-projects/spring-security/5.8.x]
    - url: ../
      branches: HEAD
      start_path: docs
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true

antora:
  extensions:
    - require: ./antora/extensions/version-fix.js
    - require: ./antora/extensions/major-minor-segment.js
