name: Merge Dependabot PR

on:
  pull_request:

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@v2
    with:
      mergeArguments: '--auto --rebase'
